* Contribution Guidelines

We are open to anyone willing to contribute. Please feel free to fork & edit as you wish. We appreciate new Input and hope to grow this filetree to eventually satisfy a broad audience.

** Basic Guide

If you want to help out and contribute to this filetree, please follow this basic flow:

1. fork this project

2. start within the *root* directory → ~/root~

3. create/extends the folder structure → e.g. ~/root/foo/bar~

4. make sure the deeply nested folder contains at least one placeholder file → 

  ~/root/foo/bar/example.doc~

5. add notes with markdown → ~README.org~ / ~notes.org~ / ~media.org~

6. If your are confident with the changes, create a pull request

  into the ~wip~ (Work-In-Progress) branch.

7. If you just want to share your personal filetree, please create a new branch on your fork with this pattern:  ~user/nickname~

** Issues

We also welcome any discussion in the *issues* section. Feel free to open a new issue if you see something missing or an error. You can also help discuss uncertain topics and contribute by posting your opinion on certain structures/namings/etc.

** Further Notes

If you are going to refactor a certain section or want to add a completely new section, we'd appreciate it that you create a feature branch for it, since that makes it a lot easier tracking the project and handling pull-requests.
