* root

The root folder defines the entrypoint for whatever storage medium might be serving it.

Usually people use an external drive, a network share exposed by a network-attached storage (NAS) or even bigger things like cluster shares.

The *root* defines several /main sections/. These main sections allow for an easy separation of content and should stay within a certain cognitive complexity.

** Overview

| folder     | contents                                                           |
|------------+--------------------------------------------------------------------|
| adult      | adult content separated into own folder.                           |
| archives   | websites, datasets, backups & dumps, ...                           |
| audio      | music, sounds, podcasts, game audio, ...                           |
| documents  | personal documents (invoices, forms, letters, ..)                  |
| images     | art, photography, fan art                                          |
| games      | board games, card games, video games, arcade, virtual reality, ... |
| literature | books, writings, scientific papers, articles, ...                  |
| software   | computer applications, mobile apps, operating systems              |
| video      | movies, short movies / films, tv shows, ...                        |

** General Advice

In this section we want to give you some general advice on things you should be aware of.

These are optional and sometimes biased. If you do not agree to them - be it partially or completely - just ignore this part.

*** Naming Files and Folders

**** Naming in General

Naming is hard. We know that. You want everything neat and tidy, but sometimes things just don't go that way - and that is perfectly fine. *Don't be afraid to break the rules and adjust this tree to your needs.*

**** Technical Issues

Some systems simply do not allow certain characters, some others do not play nice with them.

Here is a small (and incomplete) list of characters you should avoid (AKA "Forbidden Characters")

- /Please use this list as a general rule of thumb./
- /The List applies to all major operating systems./

#+begin_example
File Separators:
: (colon)
/ (forward slash)
\ (backward slash aka "backslash")

Non-alphabetical and non-numerical symbols:
¢ (Cent Symbol)
™ (Trademark Symbol)
$ (Dollar-Sign)
® (Registered Trademark Symbol)

Punctuation marks, parentheses, quotation marks, brackets and operators:
< (less than)
> (greater than)
" (double quote)
' (single quote)
| (vertical bar or pipe)
? (question mark)
,* (asterisk)

Other, rather technical "characters":
MultiSpace ("Foo.      Bar   .txt")
Tab
Newline
NUL (integer value zero)
Embedded Returns
#+end_example

* References:

- [[https://superuser.com/a/1112140][Superuser StackExchange - How to create folder name with special characters?]]

- [[https://superuser.com/questions/326103/what-are-invalid-characters-for-a-file-name-under-os-x][Superuser StackExchange - What are invalid characters for a file name under OS X?]]

- [[https://stackoverflow.com/a/31976060][StackOverflow - What characters are forbidden in Windows and Linux directory names?]]
